/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgView;

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author thomy
 */
public class frmProduct extends javax.swing.JFrame {

    /**
     * Creates new form frmProduct
     */
    public frmProduct() {
        initComponents();
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextArea getTxtAreaDesc() {
        return txtAreaDesc;
    }

    public JTextField getTxtCost() {
        return txtCost;
    }

    public JTextField getTxtPrice() {
        return txtPrice;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JButton getBtnClose() {
        return btnClose;
    }

    public JButton getBtnExport() {
        return btnExport;
    }

    public JButton getBtnGraph() {
        return btnGraph;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JList getjList() {
        return jList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtId = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblNickname = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnGraph = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDesc = new javax.swing.JTextArea();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 90, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 140, 10));

        txtId.setBackground(new java.awt.Color(32, 33, 35));
        txtId.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(null);
        txtId.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 90, -1));

        txtPrice.setBackground(new java.awt.Color(32, 33, 35));
        txtPrice.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtPrice.setBorder(null);
        txtPrice.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 140, -1));

        txtCost.setBackground(new java.awt.Color(32, 33, 35));
        txtCost.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtCost.setForeground(new java.awt.Color(255, 255, 255));
        txtCost.setBorder(null);
        txtCost.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 140, -1));

        lblName.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(51, 102, 204));
        lblName.setText("Cost");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 80, -1));

        lblPassword.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(51, 102, 204));
        lblPassword.setText("Price");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 80, -1));

        lblNickname.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblNickname.setForeground(new java.awt.Color(51, 102, 204));
        lblNickname.setText("Description");
        jPanel1.add(lblNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 120, -1));

        lblId.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        lblId.setForeground(new java.awt.Color(51, 102, 204));
        lblId.setText("ID");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/thomy/Google Drive/Training/2021/mision_tic_2022/c2_programacion_basica/c2-mision-tic-2022/semana2/reto2/informeReto2/misiontic.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        btnClose.setBackground(new java.awt.Color(244, 47, 99));
        btnClose.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 120, -1));

        btnSave.setBackground(new java.awt.Color(244, 47, 99));
        btnSave.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 120, -1));

        btnNew.setBackground(new java.awt.Color(244, 47, 99));
        btnNew.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setText("New");
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 120, -1));

        btnGraph.setBackground(new java.awt.Color(244, 47, 99));
        btnGraph.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnGraph.setForeground(new java.awt.Color(255, 255, 255));
        btnGraph.setText("Graph");
        jPanel1.add(btnGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 120, -1));

        btnExport.setBackground(new java.awt.Color(244, 47, 99));
        btnExport.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Export");
        jPanel1.add(btnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 120, -1));

        jScrollPane1.setBackground(new java.awt.Color(32, 33, 35));
        jScrollPane1.setForeground(new java.awt.Color(51, 102, 204));

        jList.setBackground(new java.awt.Color(32, 33, 35));
        jList.setForeground(new java.awt.Color(51, 102, 204));
        jScrollPane1.setViewportView(jList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 220, 360, 420));

        txtAreaDesc.setBackground(new java.awt.Color(32, 33, 35));
        txtAreaDesc.setColumns(20);
        txtAreaDesc.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtAreaDesc.setForeground(new java.awt.Color(51, 102, 204));
        txtAreaDesc.setRows(5);
        txtAreaDesc.setCaretColor(new java.awt.Color(51, 102, 204));
        jScrollPane2.setViewportView(txtAreaDesc);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 310, 210));

        btnDelete.setBackground(new java.awt.Color(244, 47, 99));
        btnDelete.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnGraph;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextArea txtAreaDesc;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
